line_length: 
  - 300 # warning

identifier_name:
  excluded:
    - to
    - id
    - by
    - of
    - at
    - !str on
    - x
    - y
    - L

disabled_rules:
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
